# Generated by Django 6.0.3 on 2026-05-15 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

import helpers.models
import memories.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Capsule",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=helpers.models.generate_unique_id,
                        editable=False,
                        help_text="unique id generator for anonymous usernames",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=224)),
                (
                    "description",
                    models.CharField(blank=True, max_length=220, null=True),
                ),
                ("log", models.TextField(blank=True)),
                ("private", models.BooleanField(default=True)),
                (
                    "maturity_date",
                    models.DateTimeField(
                        default=memories.models.get_default_expiry,
                        help_text="Time to open capsule",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor",
                    models.ManyToManyField(
                        blank=True,
                        related_name="capsules_contributed_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_capsules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ManyToManyField(
                        blank=True,
                        related_name="capsules_joined",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=helpers.models.generate_unique_id,
                        editable=False,
                        help_text="unique id generator for anonymous usernames",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("visible", models.BooleanField(default=True)),
                ("image_title", models.CharField(max_length=100)),
                ("image_file", models.URLField(blank=True, max_length=512)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memories.capsule",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Videos",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=helpers.models.generate_unique_id,
                        editable=False,
                        help_text="unique id generator for anonymous usernames",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("visible", models.BooleanField(default=True)),
                ("video_title", models.CharField(max_length=100)),
                ("video_file", models.URLField(blank=True, max_length=512)),
                ("teaser", models.BooleanField(default=False)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memories.capsule",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Teasers",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=helpers.models.generate_unique_id,
                        editable=False,
                        help_text="unique id generator for anonymous usernames",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("visible", models.BooleanField(default=True)),
                ("teaser_url", models.URLField(blank=True, max_length=512)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capsule_previews",
                        to="memories.capsule",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="preview",
                        to="memories.videos",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
