# Generated by Django 6.0.7 on 2026-07-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memories", "0002_articles_log_images_log_logs_creator_logs_stamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capsule",
            name="previous_article",
            field=models.TextField(blank=True),
        ),
    ]
