# Generated by Codex on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memories", "0003_capsule_previous_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="capsule",
            name="image",
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="logs",
            name="code_language",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="logs",
            name="code_framework",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="logs",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="articles",
            name="logs",
            field=models.ManyToManyField(
                blank=True,
                related_name="aggregated_articles",
                to="memories.logs",
            ),
        ),
    ]
