# Generated by Django 6.0.7 on 2026-08-14 20:46

import django.db.models.deletion
import django.db.models.manager
import helpers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_daily_article_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleAuditLog',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=helpers.models.generate_unique_id, editable=False, help_text='unique id generator for anonymous usernames', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('event', models.CharField(choices=[('CREATED', 'Capsule created'), ('VIEWED', 'Capsule viewed'), ('UPDATED', 'Capsule updated'), ('LOG_ADDED', 'Log added to capsule'), ('ARTICLE_GENERATED', 'Article generated for capsule'), ('MEMBER_ADDED', 'Member added to capsule'), ('MEMBER_REMOVED', 'Member removed from capsule'), ('CONTRIBUTOR_ADDED', 'Contributor added to capsule'), ('CONTRIBUTOR_REMOVED', 'Contributor removed from capsule')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsule_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='memories.capsule')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'indexes': [models.Index(fields=['capsule', 'created_at'], name='memories_ca_capsule_3ecae7_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
