# Generated by Django 6.0.7 on 2026-08-11 02:09

import django.db.models.manager
import helpers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=helpers.models.generate_unique_id, editable=False, help_text='unique id generator for anonymous usernames', primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('fullname', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_developer', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
