# Generated by Django 6.0.7 on 2026-07-21 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_sessions_access_token_user_is_authenticated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessions",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_authenticated",
        ),
    ]
